# -*- coding: utf-8 -*-
"""3mtest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a2wDqVRCE5Adyg230_z1oF6SGBIGQEza
"""

n=100
print(n+1)

"""Hej og velkommen til mit simple program."""

n=n+2 # her adderer jeg 2 til n
print(n)

s = "Henrik"
print(str(1) + s)

#for(let i = 0;i<100;i++){ } javascript

for i in range(0,100):
  print(i)
  print("HEJ")
print("Nu er vi færdige")

i=0
while (i<100):
  print(i)
  i=i+1

promille = 0.5
if promille > 0.5:
  print("sandt")
elif promille == 0.5:
  print("Du er lige netop fuld")
else:
  print("false")

